<Project>
  <!-- Enable Central Package Management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- Centralized package versions -->
  <ItemGroup>
    <!-- Code Analysis -->
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.100" />
    <!-- MAUI -->
    <!-- <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" /> -->
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.11" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="13.0.0" />
    <!-- Package reference for FlagstoneUI.Core for dependent libraries in Release builds -->
    <PackageVersion Include="FlagstoneUI.Core" Version="0.0.1-preview1" />
    <!-- Logging -->
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
    <!-- Testing -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <!-- Tooling -->
    <PackageVersion Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageVersion Include="ExCSS" Version="4.3.1" />
    <PackageVersion Include="ModelContextProtocol" Version="0.4.0-preview.3" />
    <!-- Pipeline Tools -->
    <PackageVersion Include="Acornima" Version="1.2.0" />
    <PackageVersion Include="Acornima.Extras" Version="1.2.0" />
    <PackageVersion Include="AngleSharp" Version="1.4.0" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
    <!-- Web -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="0.4.0-preview.3" />
  </ItemGroup>
</Project>